name: CMake Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  msvc-ctest:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        vs_version: ["Visual Studio 15 2017", "Visual Studio 16 2019"]

    steps:
    - uses: actions/checkout@v2

    - name: CMake (Examples + CTest + Runtime Performance)
      run: cmake -B ${{github.workspace}}/build -G "${{matrix.vs_version}}" -DCOIL_COMPILATION_TESTS=ON -DCOIL_RUNTIME_TESTS=ON -DCOIL_EXAMPLES=ON -DCOIL_RUNTIME_PERFORMANCE=ON

    - name: Build (Examples + CTest + Runtime Performance)
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --parallel 10

    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -j 10 -C ${{ matrix.config }}

    - name: Measure performance
      run: ${{github.workspace}}/build/tests/runtime_performance/${{ matrix.config }}/runtime_performance.exe
      if: matrix.config == 'Release'

  msvc-compilation:
    runs-on: windows-latest
    strategy:
      matrix:
        bindings: [COIL, MANUAL]

    steps:
    - uses: actions/checkout@v2

    - name: Cmake
      run: cmake -B ${{github.workspace}}/build -G "${{matrix.vs_version}}" -DCOIL_EXAMPLES=OFF -DCOIL_COMPILE_TIME=ON -DCOIL_COMPILE_TIME_WITH_${{ matrix.bindings }}=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --parallel 10
