name: CMake Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  msvc2017-ctest:
    runs-on: windows-2016
    strategy:
      matrix:
        config: [Debug, Release]
        clang: [true, false]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Clang
      if: matrix.clang
      run: |
        $env:CC="clang-cl"
        $env:CXX="clang-cl"

    - name: CMake (Examples + CTest + Runtime Performance)
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 15 2017" -DCOIL_COMPILATION_TESTS=ON -DCOIL_RUNTIME_TESTS=ON -DCOIL_EXAMPLES=ON -DCOIL_RUNTIME_PERFORMANCE=ON

    - name: Build (Examples + CTest + Runtime Performance)
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --parallel 10

    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -j 10 -C ${{ matrix.config }}

    - name: Measure performance
      run: ${{github.workspace}}/build/tests/runtime_performance/${{ matrix.config }}/runtime_performance.exe
      if: matrix.config == 'Release'
      
  msvc2019-ctest:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        clang: [true, false]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Clang
      if: matrix.clang
      run: |
        $env:CC="clang-cl"
        $env:CXX="clang-cl"

    - name: CMake (Examples + CTest + Runtime Performance)
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCOIL_COMPILATION_TESTS=ON -DCOIL_RUNTIME_TESTS=ON -DCOIL_EXAMPLES=ON -DCOIL_RUNTIME_PERFORMANCE=ON

    - name: Build (Examples + CTest + Runtime Performance)
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --parallel 10

    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -j 10 -C ${{ matrix.config }}

    - name: Measure performance
      run: ${{github.workspace}}/build/tests/runtime_performance/${{ matrix.config }}/runtime_performance.exe
      if: matrix.config == 'Release'

  msvc2017-compilation:
    runs-on: windows-2016
    strategy:
      matrix:
        bindings: [COIL, MANUAL]

    steps:
    - uses: actions/checkout@v2

    - name: Cmake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 15 2017" -DCOIL_EXAMPLES=OFF -DCOIL_COMPILE_TIME=ON -DCOIL_COMPILE_TIME_WITH_${{ matrix.bindings }}=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --parallel 10

  msvc2019-compilation:
    runs-on: windows-latest
    strategy:
      matrix:
        bindings: [COIL, MANUAL]

    steps:
    - uses: actions/checkout@v2

    - name: Cmake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCOIL_EXAMPLES=OFF -DCOIL_COMPILE_TIME=ON -DCOIL_COMPILE_TIME_WITH_${{ matrix.bindings }}=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --parallel 10
