name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  msvc2019:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TESTS=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 10

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -j 10 -C ${{env.BUILD_TYPE}}
      
