name: CMake Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  msvc2019:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: CMake (Examples + CTest + Runtime Performance)
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCOIL_COMPILATION_TESTS=ON -DCOIL_RUNTIME_TESTS=ON -DCOIL_EXAMPLES=ON -DCOIL_RUNTIME_PERFORMANCE=ON

    - name: Build (Examples + CTest + Runtime Performance)
      run: |
        cmake --build ${{github.workspace}}/build --config Debug --parallel 10
        cmake --build ${{github.workspace}}/build --config Release --parallel 10

    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: |
        ctest -j 10 -C Debug
        ctest -j 10 -C Release

    - name: Measure performance
      run: ${{github.workspace}}/build/tests/runtime_performance/Release/runtime_performance.exe

    - name: Cmake (Compilation time with coil)
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCOIL_EXAMPLES=OFF -DCOIL_COMPILE_TIME=ON -DCOIL_COMPILE_TIME_WITH_COIL=ON -DCOIL_COMPILE_TIME_WITH_MANUAL=OFF -DCMAKE_UNITY_BUILD=ON

    - name: Build (Compilation time with coil)
      run: cmake --build ${{github.workspace}}/build --config Debug --parallel 10

    - name: Cmake (Compilation time with manual)
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -DCOIL_EXAMPLES=OFF -DCOIL_COMPILE_TIME=ON -DCOIL_COMPILE_TIME_WITH_COIL=OFF -DCOIL_COMPILE_TIME_WITH_MANUAL=ON -DCMAKE_UNITY_BUILD=ON

    - name: Build (Compilation time with manual)
      run: cmake --build ${{github.workspace}}/build --config Debug --parallel 10
