name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-ctest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64
    - name: Verify GCC and CMake versions
      run: |
        gcc --version
        cmake --version
    - name: CMake
      run: cmake -B ${{github.workspace}}/build -DCOIL_COMPILATION_TESTS=ON -DCOIL_RUNTIME_TESTS=ON -DCOIL_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{matrix.config}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --parallel 10
    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -j 10 -C ${{matrix.config}}
